name: testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8.4
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: black
      run: black . --check
    - name: flake8
      run: flake8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Run All Tests
      run: pytest --remote-dynamo --log-cli-level debug
      env:
        ENVIRONMENT: github
        APP_VERSION: 0.1.0
